# -*- mode: python ; coding: utf-8 -*-
# vim: autoindent shiftwidth=4 expandtab textwidth=120 tabstop=4 softtabstop=4

##########################################################################
# OpenLP - Open Source Lyrics Projection                                 #
# ---------------------------------------------------------------------- #
# Copyright (c) 2008 OpenLP Developers                                   #
# ---------------------------------------------------------------------- #
# This program is free software: you can redistribute it and/or modify   #
# it under the terms of the GNU General Public License as published by   #
# the Free Software Foundation, either version 3 of the License, or      #
# (at your option) any later version.                                    #
#                                                                        #
# This program is distributed in the hope that it will be useful,        #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU General Public License      #
# along with this program.  If not, see <https://www.gnu.org/licenses/>. #
##########################################################################
"""
PyInstaller spec for building OpenLP as a Windows one-folder bundle.

Intended to be run via Wine on Linux:
    wine python -m PyInstaller scripts/openlp_windows.spec

Or via the helper script:
    hatch run build-windows
"""
import os
from PyInstaller.utils.hooks import collect_dynamic_libs

# SPECPATH is set by PyInstaller to the directory containing this .spec file.
ROOT = os.path.abspath(os.path.join(SPECPATH, '..'))
pyside_binaries = collect_dynamic_libs('PySide6')

a = Analysis(
    [os.path.join(ROOT, 'openlp', '__main__.py')],
    pathex=[ROOT],
    binaries=pyside_binaries,
    datas=[
        # Web display engine (HTML/JS/CSS served to the Qt WebEngine)
        (os.path.join(ROOT, 'openlp', 'core', 'display', 'html'),
         'openlp/core/display/html'),
        # Compiled Qt resources (generated by generate_resources.sh)
        (os.path.join(ROOT, 'openlp', 'core', 'resources.py'),
         'openlp/core'),
        # Translations
        (os.path.join(ROOT, 'resources', 'i18n'), 'resources/i18n'),
        # Images / icons
        (os.path.join(ROOT, 'resources', 'images'), 'resources/images'),
        # UI form definitions
        (os.path.join(ROOT, 'resources', 'forms'), 'resources/forms'),
    ],
    hiddenimports=[
        # Plugins are discovered at runtime via importlib / pkg_resources
        'openlp.plugins.alerts',
        'openlp.plugins.alerts.alertsplugin',
        'openlp.plugins.bibles',
        'openlp.plugins.bibles.bibleplugin',
        'openlp.plugins.custom',
        'openlp.plugins.custom.customplugin',
        'openlp.plugins.images',
        'openlp.plugins.images.imagesplugin',
        'openlp.plugins.media',
        'openlp.plugins.media.mediaplugin',
        'openlp.plugins.obs_studio',
        'openlp.plugins.obs_studio.obs_studio_plugin',
        'openlp.plugins.planningcenter',
        'openlp.plugins.planningcenter.planningcenterplugin',
        'openlp.plugins.presentations',
        'openlp.plugins.presentations.presentationplugin',
        'openlp.plugins.songs',
        'openlp.plugins.songs.songsplugin',
        'openlp.plugins.songusage',
        'openlp.plugins.songusage.songusageplugin',
        # SQLAlchemy dialects used by OpenLP
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.mysql',
        'sqlalchemy.dialects.postgresql',
        # Windows-specific
        'win32api',
        'win32con',
        'win32gui',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude Linux / macOS only packages
        'distro',
        'Pyro5',
        'pyobjc',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='OpenLP',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon=os.path.join(ROOT, 'resources', 'images', 'OpenLP.ico'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='OpenLP',
)
